### ISSUE TITLE
Overview is not a textarea box and doesn't accept HTML

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/VIVO#3]
Drew and I remember this working on the dev version of VIVO, so I'm not sure what changed.

Are we missing an n3 file?

I can post this to VIVO Slack.

<img width="1102" alt="Screen Shot 2020-12-03 at 8 07 02 AM" src="https://user-images.githubusercontent.com/3651640/101022068-e0299c80-353e-11eb-985f-8f69a393df75.png">

**Comment by paulalbert1** [comment]
Looks like this partially fixes it.

<img width="934" alt="Screen Shot 2020-12-03 at 8 38 45 AM" src="https://user-images.githubusercontent.com/3651640/101025067-06e9d200-3543-11eb-9163-e13c49c1ac60.png">

**Comment by sarbajitdutta** [comment]
Fixed
